services:
  - type: web
    name: cityarts-scraper-service
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SCRAPE_SHARED_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GIT_USER_NAME
        value: cityarts-scraper-bot
      - key: GIT_USER_EMAIL
        value: scraper-bot@users.noreply.github.com
